### ISSUE TITLE
Slonik depends on array parser which is removed from pg-types 3.0.0

### ISSUE THREAD

**Issue by trungduyvu** [gajus/slonik#168] opened 2020-04-15 05:53 UTC
`createTypeOverrides.js` imports arrayParser from pg-types 3.0.0 and use it in the following code

```
 if (postgresType.typarray) {
      typeOverrides.setTypeParser(postgresType.typarray, (value) => {
        return arrayParser
          .create(
            value,
            typeParser.parse,
          )
          .parse();
      });

```

arrayParser is removed from pg-types 3.0.0 https://github.com/brianc/node-pg-types/commit/09ea6256a4addca199d45db850e59ce50e330d34

## Expected Behavior
Array should be parsed correctly

## Current Behavior
Throws exception

## Steps to Reproduce
1. Create a table that has a int8[] column
2. Run a query against the table

**Comment by gajus** [comment] 2020-04-15 06:43
Seems like an easy PR to make.

**Comment by felamaslen** [comment] 2020-06-08 16:32
How is this not a bug? This can also be reproduced by using `array_agg`, e.g. by running the following query:

```js
import { sql } from 'slonik';
connection.query(sql`
SELECT id, array_agg(column) as columns
FROM table
GROUP BY id
`);

**Comment by gajus** [comment] 2020-06-08 16:51
None of the tests are failing, so that's why it is not a bug.

Please add a test case that is failing or document the expected/ actual behaviour.

**Comment by felamaslen** [comment] 2020-06-08 16:53
The above is documented in this issue already, for two separate cases.

**Comment by gajus** [comment] 2020-06-08 19:48
Fixed in https://github.com/gajus/slonik/issues/182.

**Closed** 2020-06-08 19:48 UTC
Labels: enhancement, help wanted
