### ISSUE TITLE
Getting "Expected `activeQueryPromise` to be set." error

### ISSUE THREAD

**Issue by mirandaio** [gajus/slonik#648] opened 2024-10-22 13:06 UTC
I have some code that is inserting rows into four different tables in a transaction and sometimes it throws this error:

`Expected activeQueryPromise to be set.`

I found this error is thrown in this part of slonik [code](https://github.com/gajus/slonik/blob/main/packages/driver/src/factories/createDriverFactory.ts#L395) but I'm not sure why it is happening or how to prevent it from happening.

## Expected Behavior
Complete the transaction successfully

## Current Behavior

It throws this error:

`Expected activeQueryPromise to be set.`

## Steps to Reproduce

Code looks roughly like this:

```js
const table_a_rows = [...];
const table_b_rows = [...];
const table_c_rows = [...];
const table_d_rows = [...];

await pool.transaction(async (transactionConnection) => {
  await transactionConnection.query(sql.unsafe`
    INSERT INTO table_a (id, bar, qux)
    SELECT * FROM ${sql.unnest(table_a_rows, ['uuid', 'int4', 'timestamp'])}
  `);
  await transactionConnection.query(sql.unsafe`
    INSERT INTO table_b (id, b)
    SELECT * FROM ${sql.unnest(table_b_rows, ['uuid', 'int4'])}
  `);
  await transactionConnection.query(sql.unsafe`
    INSERT INTO table_c (id, c)
    SELECT * FROM ${sql.unnest(table_c_rows, ['uuid', 'int4'])}
  `);
  await transactionConnection.query(sql.unsafe`
    INSERT INTO table_d (id, d)
    SELECT * FROM ${sql.unnest(table_d_rows, ['uuid', 'int4'])}
  `);
});
```

**Comment by gajus** [comment] 2024-11-11 21:34
Can you create a PR that replicates a test showing this error?

**Comment by gajus** [comment] 2024-11-14 15:20
Cannot reproduce. Happy to work on it if reproduction is provided.

**Comment by mirandaio** [comment] 2024-11-14 15:43
Thanks for looking into this. Will try to provide a reproduction.

**Comment by gajus** [comment] 2024-11-15 15:12
Closing until there is a reproduction.

**Closed by gajus** 2024-11-15 15:12 UTC
Labels: needs-replication

**Comment by benkroeger** [comment] 2024-11-29 16:10
I just ran into the same issue - was caused by the type parsing of one individual query in the transaction throwing an error.
Basically unhandled thrown errors in the transaction 'callback' cause this.
Add some try/catch to your code and see where it fails exactly.

**Comment by gajus** [comment] 2024-11-29 17:03
> I just ran into the same issue - was caused by the type parsing of one individual query in the transaction throwing an error. Basically unhandled thrown errors in the transaction 'callback' cause this. Add some try/catch to your code and see where it fails exactly.

Just to clarify, the unhandled errors are stemming in user code, not library code?

If it is from the library code, please share stack trace.

**Comment by benkroeger** [comment] 2024-11-29 17:10
yes, user code...but it gets swallowed / hidden by the transaction wrapper---Mit freundlichen Grüßen Benjamin KrögerAm 29.11.2024 um 18:03 schrieb Gajus Kuizinas ***@***.***>:﻿

I just ran into the same issue - was caused by the type parsing of one individual query in the transaction throwing an error. Basically unhandled thrown errors in the transaction 'callback' cause this. Add some try/catch to your code and see where it fails exactly.

Just to clarify, the unhandled errors are stemming in user code, not library code?
If it is from the library code, please share stack trace.
I have never seen this though, so feels like user code.
