### ISSUE TITLE
[TypeScript] Cannot use interface type because of ExternalQueryResultRowType constraints

### ISSUE THREAD

**Issue by davidskuza** [gajus/slonik#270] opened 2021-04-09 09:34 UTC
If we want to query using simple plain interface TS compiler complains about type constraints: 

Type 'TestInterface' does not satisfy the constraint '**ExternalQueryResultRowType**'.

## Expected Behavior
To work

## Current Behavior
Doesn't work

## Steps to Reproduce
[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbABSgEsBbEmEgN2ADV1UBXYAUXCwGdOSIA7ACr5sAXjgAjCBFTB0fOAB84fJmXHAoiuJxik+Acy1Z0Cfqlxxi5SjXqMW7MFx78hBANoBdLStSoA3ABQoJCwiCgYWDjCcACKLFC4AErAnEyoMEkQAO4AwtKqgjFiVhRUtAzMbBypLkUEQUhomNh4BHDsMBp8jPEayanpmTluonApyNAIADw6evoANHEJA2kZWXkFZPXAAHxBIdDwTZGtMX2JAIJ8uABiTHzIVK7FcNMCcKBdfAicHSBdKA9VAXVZDDajOBiTrdXorFJrYbZUa7AAUnAAjqgAFzaXQkAwASihu0sUAgFE4wGmxlMfHMcAEXn2gWC4CO4WaUTa2HyZDI-FBAFlgDAABYQX6QsQAb0CcAVcFpZgsclwuNB1zuDyevB2QQAvkE2aFjhEWtF2gARdAwdDidBUwhSVDSuB8gV8YWiiVS4SBI2sw5hE4WyZ8HRwZDGLrO6S41HhvgoZ58ACqpFxcwJ+mJIlJNrtDqdLtGxoJgIAZuhkNgBKkYABJPhVmvAAByEBgAHVoABrHNwOUKyskYCoBBZ-EGQ2sisaau1xkN5ut2u9qADgxD+VwUfjyd4+ZBBXuADSU-mng18MG6xy+WY21GAdZjtwjz3OtTcDI6AJqLEsOUb8JGkDSFCUYxsAcaoKiABEAB0yHwYSxoKgA9BhjIxAA5PWOirguba4YgECpMoXbaLaJCcJWFjitg4ZzP+LZwLhMJAnC-QIuCIzCLhiG7lhirNkgIDaCQ+g9DATBRLRv60Tw24Epa2D4SuLbEbWgkwJwqIAEwAMwACwmYSu7oNk-7wOBqCIWq7yaWuHZdhuW76GiAAGXloZZ1mUHAdkOTcTmEVpUCLsA7k5t5vmzkAA)

**Comment by nponiros** [comment] 2021-04-17 09:28
I got a similar error after upgrading to 23.6.4 and using the various query methods (any, one, etc.). Mine was: "Type 'XXXXX' does not satisfy the constraint 'Record<string, PrimitiveValueExpressionType>'". The reason for the difference is the older typescript version I use. I have 4.1.2, in the playground 4.2.3 is used.

Also this seems to be a duplicate of https://github.com/gajus/slonik/issues/268 which mentions the exact same type error as this issue.

**Comment by adevine** [comment] 2021-05-31 19:40
Hi @gajus - I looked through the commit history, and saw your commit 09c7db1, but note that did not fix this bug for me. The issue is that whenever I call one of the query methods as follows, e.g.

```
pool.one<{ id: string; someJsonField: MyJsonType; }>(sql`SELECT id, someJsonField FROM ...`);
```

I still get the following error:

Type '{ id: string; someJsonField: MyJsonType; }' does not satisfy the constraint 'ExternalQueryResultRowType'.
  Property 'someJsonField' is incompatible with index signature.
    Type 'MyJsonType' is not assignable to type 'PrimitiveValueExpressionType'.

My suggestion is to just completely revert https://github.com/gajus/slonik/pull/265 first - as evidenced by all of the bugs that came in after it, it was a breaking change. But more importantly, the very premise of that pull request was incorrect, given that it's possible to return a JSON column in one of the ...First methods. That is, unlike what is written in that PR, it is perfectly valid for me to do something like

```connection.anyFirst<{ foo: number }>(sql`...`)```

because I could be returning a column that represents a JSON value.

**Comment by acro5piano** [comment] 2021-06-10 05:57
Still happening on v23.8.0.

**Comment by davidskuza** [comment] 2021-06-10 06:10
TypeScript rewrite considered failure.

**Comment by khrykin** [comment] 2021-06-25 15:06
Why do we need the constraint on the query result type in the first place?

**Closed** 2021-08-06 23:28 UTC
Labels: bug
